/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 14.09.2026 19:22:14

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1440;
#else
constexpr int kTensorArenaSize = 416;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,39 } };
const TfArray<1, float> quant0_scale = { 1, { 0.052597165107727051, } };
const TfArray<1, int> quant0_zero = { 1, { -4 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { -49, 222, -293, 32, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0004530955629888922, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*16] = { 
  39, 41, 98, -17, 3, -50, -127, -20, 84, 47, -15, -69, -29, 59, -19, -125, 
  55, -33, -89, -86, -113, -58, 24, 35, -37, 18, 118, 60, 40, -13, 34, 42, 
  -97, 77, -67, -114, 77, -75, 60, 48, 48, -79, 36, -1, 8, 12, 20, 39, 
  4, -38, 33, 66, 46, -20, 74, -51, -95, -85, -66, 16, -70, -40, 66, 100, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,16 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0078646047040820122, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[16] = { 1069, -217, -129, 263, 340, 347, 110, 30, -110, 238, -143, 462, 7, -82, 347, 499, };
const TfArray<1, int> tensor_dimension3 = { 1, { 16 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00014281200128607452, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[16*64] = { 
  31, 43, 76, 48, -14, -22, -36, 29, 17, 44, 14, 4, -43, 9, 36, -51, 12, 7, 43, 75, -42, 8, 59, 32, 37, 29, 56, 41, 65, 27, 4, -48, -67, -4, 20, 4, -56, -27, 44, -42, -14, 75, 99, 28, 15, 103, 34, -42, -30, 30, -66, 33, -21, 39, 77, 26, 95, 57, 64, -15, -87, 27, -19, -90, 
  -32, 47, -8, 62, -5, -17, 24, 34, -39, -33, -14, 8, 55, 65, 39, 69, 66, 30, 24, -40, -19, -2, -3, 27, -10, 41, 31, -12, -55, -79, 56, 0, -58, 60, 54, 31, 11, 32, 29, -39, 35, -33, -56, -40, -45, 28, -48, -26, -47, -9, 81, -69, 68, 50, -22, -25, -67, -53, -39, 18, 54, 34, 10, 11, 
  -28, 21, -24, 26, 2, -41, -34, 43, 60, -12, 36, 36, 37, -65, -28, 74, -55, 29, 87, -80, -13, -8, 54, 4, 37, 35, -32, 22, -50, 3, 59, 36, -11, 56, 4, -26, 60, -84, -42, -37, -17, -69, 107, 16, 20, -40, -15, -39, 14, 27, -3, 11, -54, 36, -57, -20, -66, 84, -3, 65, 24, 21, 48, 28, 
  38, -29, 27, -10, 31, -24, -89, 52, 20, -46, -13, 46, 15, -57, -43, 58, -48, 32, 1, -69, 33, -58, 40, -14, 51, -57, 17, 32, -15, -1, -9, -20, 45, -7, -30, -30, -11, -40, 10, 69, -30, 32, 102, 59, 19, -102, 49, 87, 39, 18, 79, -40, 28, -12, 25, -24, -64, 8, -89, -12, -10, -37, 30, 48, 
  -41, -13, -36, -39, -48, -37, -1, 30, -36, -15, -13, -54, -11, 45, 17, -19, 35, 32, 34, -45, 9, 57, -33, 37, -30, -24, -21, 31, 40, 14, 67, -4, 17, 90, 1, 7, -55, 75, -67, 22, -31, -35, 15, 6, 57, -14, 40, -7, -41, -10, -18, 0, -11, -14, -6, -37, -9, -21, -38, 40, 3, 7, -19, 83, 
  -24, 33, 35, 17, -13, -71, -91, 69, -34, 27, -18, -22, 35, -7, -69, 6, -47, 57, 34, -36, 10, -29, -25, -1, -2, -4, -15, 12, 6, 24, -6, -65, 21, 1, 14, 4, 34, -24, 29, 47, 26, 70, 34, 67, -6, -59, 19, 47, 33, 6, -39, 32, -62, 40, -3, -18, 1, 43, -83, 28, 21, -39, 36, -15, 
  54, 0, 24, -4, -43, 8, 45, 10, 11, -31, 36, -66, -13, 1, 27, 20, -10, -44, -70, 6, -10, 4, -47, -51, -33, -10, 50, -16, -58, 30, -45, -19, 127, -2, -58, -50, 13, 77, 13, 21, 28, 78, -11, -45, 40, -34, 43, 97, 46, -25, 27, -38, -43, 27, -23, -58, 56, -15, 25, -49, 58, 22, -20, 85, 
  -3, 41, 4, -57, -37, 76, 105, 9, 14, 49, 49, 41, 36, 69, 62, 3, 38, -5, -67, 50, 40, 59, 38, 39, -2, 76, 18, -67, 46, -45, 14, 45, -43, 38, 2, 60, -29, 112, 42, 22, -30, -20, -65, -32, -33, 26, -34, 14, -40, -37, -8, 13, 27, -22, -19, 41, -8, -68, 85, 19, 57, 7, -61, 9, 
  18, -60, 32, 68, 3, 2, 47, 37, -27, -42, -57, 43, 48, 15, -61, 78, -12, -9, 60, 72, 6, 26, -23, 2, 10, -29, 55, 11, -8, -56, 55, -29, -57, 40, 1, 13, 39, 23, -7, 37, -48, -79, -10, 13, -29, 30, 47, 16, -25, -43, 63, -48, 31, 24, 5, -19, 29, -42, 5, -34, 61, -52, -18, 13, 
  12, -16, 32, 56, -15, 47, 23, 12, -13, -9, 1, -41, -1, 31, -20, 11, 6, -39, 14, 104, -19, 60, -10, 80, -3, 55, -36, -48, -13, 28, -15, 57, -72, -25, 51, -13, 27, -11, -18, -45, -58, 10, 24, 1, -63, 88, 24, -69, -46, 63, -59, 8, 27, 8, -16, 14, 24, -61, 13, 9, -78, 17, -67, 24, 
  -44, -22, -25, 40, 14, -33, 33, -14, -27, -37, -2, 10, -53, -44, -76, 10, 13, -3, -31, -2, -27, -6, -13, 68, 9, 6, 7, 1, 25, 31, 64, 35, 55, -85, 41, -21, -50, 10, 57, 41, 0, 35, -59, -15, 22, 24, -35, -91, 24, 10, -23, 15, 61, -48, 52, 28, -64, 24, 121, -13, 63, 46, -64, -27, 
  -43, 20, -15, 25, 34, 10, -41, -25, 5, -31, 17, 39, 37, -54, -7, -7, -17, -10, -68, 100, -62, -35, -29, -26, 53, 46, 32, -56, 46, -4, -13, -59, 22, -6, -77, 9, -78, 48, -25, -68, 20, 13, -69, -22, -91, -39, 27, -23, -9, -28, -31, 81, 29, -4, -29, -34, 92, 39, 21, -47, 2, 1, -27, 15, 
  -45, 27, -39, 49, -14, -7, 42, -11, 24, -10, -41, -22, -46, 28, -41, -18, 25, 26, 32, 12, 24, -49, -27, 26, -46, -33, -13, -16, 16, 25, 7, 15, 31, 1, -18, -11, 15, -34, 0, -14, 1, 14, 30, -8, 9, -26, 5, 38, -10, -51, -29, -41, -5, -1, -19, 0, -23, -28, 7, 24, 3, -2, 9, -43, 
  3, -9, -16, -27, -49, 31, -27, -25, 29, 20, -26, -1, -52, -43, -28, -40, -29, 5, 46, -2, 34, -42, -37, 28, -11, 4, 0, -45, 34, -29, 4, -3, -19, 5, -52, -46, -47, 51, 28, 37, -30, -52, 30, -48, 24, -5, 16, 23, -11, 25, -51, 33, -38, 3, -51, -31, 10, 13, 16, -6, 33, -19, -37, 2, 
  44, 4, 44, -45, -10, 24, 30, -20, -9, 52, 50, -3, -6, -17, 37, -35, 41, -52, -16, 9, 10, -62, 6, -64, 52, -41, -12, -12, -65, 71, 8, -48, 120, 29, 15, 12, 16, 21, 42, 23, -17, 68, -43, -36, 47, -12, -39, 58, 13, 23, 8, -24, -25, 52, -14, -53, -21, -19, 46, -32, 68, -38, 10, 1, 
  52, 27, -4, -24, 8, -36, -36, 45, 5, -4, 28, -14, -12, -29, 30, 11, -26, -40, 55, -56, -37, -23, 8, 15, 34, -56, 34, -19, 8, 73, 14, 16, 37, -48, 33, -15, -48, 86, -2, 63, 81, 28, 61, -41, 78, 13, -25, 10, -8, -18, -32, -48, -41, -55, 45, 60, 33, 21, 113, 48, 44, -40, -1, -26, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 16,64 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0052970941178500652, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[64] = { 495, 335, 857, 2, -223, 118, -591, 337, -69, 284, 307, -296, -323, -179, 203, -171, 297, -175, -220, 462, -126, -197, 112, -74, 195, 194, 278, 348, 194, 481, 143, -529, -28, -20, 38, -34, -236, 303, 353, -104, -231, 753, 664, -135, 261, 185, 326, 403, -70, 138, -336, 86, -151, 48, 694, 31, 353, 226, 89, -40, -210, -2, -152, -105, };
const TfArray<1, int> tensor_dimension5 = { 1, { 64 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00023197973496280611, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[64*39] = { 
  54, -64, 11, 44, 20, 12, -6, 58, -23, -43, 13, -34, -39, 29, 7, -49, 57, 23, 25, -3, 17, 102, -23, 28, -36, 12, -49, -11, 37, 56, 45, -64, -48, -35, -14, -2, -10, 44, -23, 
  -10, -65, -37, 23, -21, 33, 13, 17, -61, -11, 43, -56, -18, 26, 64, 2, 12, -13, 31, 7, 0, 51, -29, -44, -61, -6, 54, -21, -84, -25, -27, 39, -40, 43, 40, 47, 11, 32, -17, 
  91, -48, 36, 47, -47, 19, 52, -44, -43, -66, -2, 12, -62, 76, -38, -6, 74, 41, 20, 19, 21, 60, 52, -44, 21, 12, 20, -36, 31, 58, -4, -20, 27, -2, 18, -23, -14, -28, -31, 
  -94, 41, 58, 26, 55, -47, 36, 45, -16, 14, 49, -58, 17, -32, -6, -7, -23, 46, 18, -43, -27, -58, -30, 64, -59, 3, -21, -43, 61, -37, -21, 53, 48, -41, -5, -28, -43, 3, 10, 
  33, 6, -30, -58, -37, 39, 20, -25, -7, -38, 58, -4, -35, -20, 35, -14, -60, -24, -14, -21, 5, 36, 1, 51, 32, 48, -37, -38, -14, 31, -1, -38, 15, 30, -33, -36, 43, 45, -5, 
  9, 49, -88, -11, 2, -74, -36, 2, -49, -41, 48, 4, 23, -19, 1, -13, 55, 45, -53, 27, 35, -34, -17, 76, -10, -38, -34, 23, 31, 35, 0, -31, -9, -82, 1, 20, 21, 25, 36, 
  -57, -62, -4, -43, 40, -83, -31, -64, -73, -55, -1, 27, 13, -33, 12, -42, -53, -22, -52, -52, 0, 50, 24, -3, 46, 28, -45, 5, -21, -28, -5, 9, -24, -39, -30, 57, 24, 36, -37, 
  23, -6, -19, 63, 64, -16, -27, -72, -19, 13, -14, -25, 9, -17, -67, -17, 40, 4, -44, 54, -11, -42, -67, -16, 44, 49, -33, -22, -1, 1, -17, -17, 55, 32, -10, 11, -35, 0, 3, 
  11, -20, -18, -5, -41, 57, -10, 26, -22, -46, -17, 37, -13, -20, 1, -45, -51, -12, 79, -4, 1, 20, -53, -46, -13, -31, 25, 0, -5, 27, 46, -20, -4, -13, -8, -32, -3, -44, 28, 
  -4, -24, 8, -32, 10, 1, -11, -29, -9, 57, -36, 12, 31, 52, -39, 53, 40, 40, 43, -85, 16, 59, 69, -29, -29, 16, -10, -18, 14, 55, -22, -36, 20, 77, 87, -21, 36, -13, -25, 
  95, -5, -14, -30, 32, -8, -45, -26, 45, 7, -53, -40, -44, -38, -22, 25, 47, 58, 9, 22, 43, 58, 22, -22, 34, -11, -26, 48, -65, 69, -33, 55, 7, 61, 3, 4, 23, -59, 44, 
  -63, -55, 14, 37, 23, -27, 17, 31, -39, -15, 0, 14, 5, -2, -11, -61, -22, 24, -28, -26, 14, -66, -64, 10, 49, 48, 51, 41, 47, -57, 5, 24, 46, 18, -38, 16, -25, -23, 19, 
  -82, 10, -15, -29, -14, -15, -45, -25, 21, -54, -55, -38, -47, -60, 18, 0, -20, 40, 33, -27, -31, -57, -50, 34, -13, -6, -20, 3, -32, -20, 37, -26, 19, -66, -17, 8, 17, 18, -42, 
  -34, 5, -3, -64, -4, -104, -57, -42, 2, 25, -38, 34, -52, -58, -51, 21, -43, -66, 0, -59, 29, 26, -6, -31, -5, -20, 19, -53, 5, -9, -22, -60, 9, 52, 27, 9, 69, -26, -33, 
  77, -120, 75, 9, -12, -86, 13, -60, 38, 26, -25, 27, -56, -1, 83, -90, -28, -31, 28, 16, 38, -17, -40, 3, -57, 30, 1, 22, -56, -10, 49, -26, -38, -24, -9, 62, -49, 21, -29, 
  -35, 19, 64, -22, 40, 8, -9, -44, -25, 13, -35, 4, 29, 38, -70, 30, 11, -34, 8, -18, -45, -67, -30, -10, 8, -57, -82, -27, -11, -50, -26, -106, -56, -30, -66, -84, -24, -7, -14, 
  45, 1, -35, 6, 25, -76, 46, -16, 24, -16, 44, -53, 3, -49, -22, -11, 29, 55, -7, -84, -29, 41, 41, 4, 29, -15, 9, -31, -11, 28, 0, 0, -11, -19, 48, 60, -2, 11, 2, 
  -40, -24, 48, -44, 24, -15, 5, -18, 5, 6, 0, -35, 59, -39, -56, -44, -7, 31, -38, -22, -30, 16, -26, -15, -38, -37, 1, -15, 74, 16, 20, -1, -33, -57, 34, 16, 0, -40, -23, 
  -83, 47, 19, -50, 40, 11, 47, 38, -25, -26, -42, -53, 50, -13, 4, 3, -12, 14, 24, 2, 29, -21, 61, 1, 28, 28, -46, 85, -13, 28, 38, -127, -40, 11, -30, -89, -12, -27, -20, 
  25, 115, 10, 56, 12, -2, -38, 6, 15, -31, 49, 51, -35, 39, 49, -24, 8, -16, 4, -8, -53, -90, 45, 70, 90, 24, -10, 9, 23, 49, -69, -67, -72, -63, -23, -64, -49, 44, -37, 
  -19, -41, -20, -22, 16, 36, -5, 26, 10, 45, -38, -11, 11, -54, -33, -34, -50, 17, -25, 38, -33, -52, -18, 16, 14, -1, 14, 27, -34, 3, 24, -22, 18, -4, -27, 43, -11, -7, 27, 
  -1, 37, -20, 2, 29, 58, -24, 61, -15, -9, 66, 47, 15, 44, -42, 32, 8, 6, 28, -19, 13, 72, 91, -13, 1, -53, -4, -40, 5, -46, -49, -20, 31, 20, -28, 44, 68, 60, -9, 
  -39, -44, -23, 67, -24, 63, -23, 43, -5, -43, -46, -50, 17, -38, 10, -20, -51, 36, 77, -13, 12, -57, -4, 34, 6, -28, -20, 7, -49, -11, 36, -11, 56, 63, 30, -58, 22, -38, 10, 
  26, 26, -73, 2, 12, -7, 41, -8, -24, 50, -17, -22, 16, 13, -27, 33, -20, 28, -37, -21, -75, -30, 40, 37, -53, 12, 35, 40, -25, 11, 18, -6, 73, 12, 59, 74, 73, 18, 8, 
  1, -55, -63, -31, 6, 71, 49, 32, -11, 0, -60, -50, -27, 18, -26, 40, 60, -59, 37, 42, 2, 18, -58, 18, -10, -44, 38, -40, 9, -12, -18, -50, 6, 31, 7, -31, -1, 14, -35, 
  26, 8, 42, -12, 33, -12, -12, -23, -50, -33, -36, 26, -30, 31, 91, 35, -42, -8, -26, -46, -16, -75, -17, -5, -27, 1, -43, 45, 24, 12, 17, 47, -51, -56, -20, -26, 7, -91, 12, 
  18, -52, 39, -40, -7, -58, -52, 28, -14, -34, -18, -29, -62, -40, -42, -18, -3, -47, -43, -5, 18, 31, -58, -51, -40, 32, -14, -8, -21, 63, -40, 45, 34, -22, -28, -56, -21, 48, -23, 
  -27, -27, -9, -25, 25, -8, -5, 26, -28, -21, -56, -33, 55, 28, -32, 77, 16, -48, -40, 37, -14, -32, 29, -21, 0, -60, -40, 21, -68, 32, -80, -19, -9, -37, -51, 7, -42, 14, 30, 
  76, -26, -65, 24, -46, -23, 57, -3, -18, 27, -2, 38, -7, -18, 30, 23, -42, -33, 36, 10, -44, 7, -9, -41, -53, -18, 74, -25, 10, 39, 27, -12, -1, 27, -14, 18, -22, -59, 54, 
  79, -2, 48, 52, 39, 61, -49, 58, 33, -23, -27, 18, -45, 45, -26, -36, -10, -30, -47, 44, -24, 61, -46, 30, 17, 47, 27, 7, 11, 18, -61, 0, -51, -19, -4, -36, 12, -11, -40, 
  -4, 65, -19, 21, 35, -7, 34, 20, 20, 36, -16, -49, -21, -13, 27, 72, 12, -46, -41, 19, -87, -49, 40, -33, 23, -38, 1, 6, 37, -40, -12, -47, 18, 35, -2, 37, 82, -26, -41, 
  -19, -46, -10, 21, -52, -35, -68, -55, 35, 27, -3, 0, -10, 19, 55, -15, 15, -25, -27, -16, -2, 8, 24, 15, -24, 27, 58, 31, -24, -58, 28, 45, -38, -35, -45, 23, -2, -6, 35, 
  -62, 97, 31, 1, -4, -34, -49, -64, 41, 24, 36, 20, 23, -18, -14, 75, 4, 77, 45, 55, -19, 13, -51, 64, 4, 23, -11, -54, -13, 55, 23, 19, -32, 11, -42, -15, -2, 27, -17, 
  -92, 50, 13, -25, -46, -51, -6, -8, -24, -32, -51, 48, -35, -11, 51, 63, 50, -57, -3, -32, -21, -43, 24, -33, -49, 5, 17, 17, -20, -2, 51, 32, -44, -73, 16, 19, 60, 39, 7, 
  -38, 38, 14, 6, 43, 32, -28, 12, -42, -42, 46, 7, 20, -9, 6, 14, 14, -1, -32, -14, 32, 14, 56, 56, 9, -11, 42, -43, 32, -5, 36, -58, 55, -31, 26, 41, 23, -53, -10, 
  29, -44, 32, 50, -12, -22, -29, 12, 0, -19, 29, -60, -63, 24, 47, 16, -46, -44, -76, -42, 20, -84, -31, 0, 15, -22, 1, 39, -5, 23, 30, 7, -47, -58, -5, -4, -14, -62, -41, 
  -78, 70, 0, 29, -3, -30, -44, -39, -18, -21, -33, 34, 11, -48, 47, 32, -16, 62, -58, -91, -59, -57, 30, -39, -50, 15, -3, 21, -58, -40, 16, -72, 50, -19, -2, -36, 27, 77, -16, 
  53, 0, -31, -25, 11, -28, -19, 56, 18, 32, 11, -6, 30, -5, -57, 51, -10, 15, -9, -54, 5, -14, -8, -57, -8, -71, 31, 60, 16, -30, -23, 72, 16, 9, 80, 5, 15, -77, 42, 
  43, -55, -22, 28, -50, -32, -41, -13, -22, 53, -60, -17, -20, -14, -3, -65, 15, 15, -7, -43, -6, 27, -3, 56, -10, 14, 22, -29, 59, -24, 14, -43, 51, -31, 1, -28, 56, -30, -50, 
  41, -6, -26, 50, 41, -56, 9, -23, 21, 22, -35, -53, -9, -1, -88, -7, -62, -70, -58, 28, -12, -11, -19, 29, 45, 4, -42, 22, -44, 43, -41, 12, -11, 50, 22, -9, -1, -12, 3, 
  -1, -43, -1, -63, -24, -30, 48, 33, -30, 14, -52, -56, -31, -51, 97, -37, -13, 18, -18, -44, 12, 7, -18, -72, -30, -18, -11, 50, 51, 12, -31, -52, 9, 64, 28, -3, -38, 40, -24, 
  122, -65, -34, 45, -27, 82, -21, 66, 43, -17, 16, -45, 4, -17, -11, -56, 5, 31, -4, 72, 75, 70, 28, -74, 16, -42, -39, 20, 2, 63, 7, 1, -11, 9, -53, -23, -50, 31, -32, 
  4, -91, 49, -8, 1, -2, 9, 45, -33, 25, -20, 45, 49, 52, -10, 88, 39, -64, -80, -62, -37, -73, -33, 4, -28, 18, 6, -59, 52, -56, -13, -4, 10, -17, 0, 1, -19, -4, -29, 
  -79, 13, 32, 27, 8, 9, -52, 6, -23, -48, 34, 15, 23, -18, -89, -68, 8, 40, 69, -18, 33, 44, -31, 46, -37, 55, -45, -44, 94, -4, 34, 37, 45, 8, 42, 4, -30, 14, -33, 
  60, 0, -48, -6, 48, 84, 72, 51, 43, 0, -28, 40, -11, 22, 49, 77, -19, -25, -73, -84, -76, -23, -7, -30, 33, -5, 13, -8, 72, 10, -29, -40, -30, 35, -3, 42, -80, 18, -32, 
  58, 78, -35, 56, -36, 62, 67, -4, 28, 60, 11, 36, 38, 12, -69, 11, -34, 49, 21, -17, 7, 88, 102, 60, 66, -44, 55, 7, 24, 51, 2, -35, 11, 52, -8, 71, 61, 42, 30, 
  -20, 11, 29, -12, 28, 48, 24, -57, -17, 22, -53, -43, -52, 64, -92, -46, 11, 41, 77, 77, -14, 9, 27, 10, -43, 4, 30, -60, 53, 29, -61, 25, -47, -44, 12, 5, 51, -25, 5, 
  50, -88, 29, 64, 6, -15, -1, 14, -26, 12, -40, 15, 29, 54, -42, -50, 28, 30, 60, 83, 22, 53, 44, 38, 80, 38, -73, 7, 11, -18, 3, -7, -14, -38, -26, 39, 37, -3, -12, 
  22, -52, 48, -48, 33, 59, 22, 20, -35, -37, -55, -29, 14, -37, 32, -64, 8, -17, 18, 88, 64, 74, -42, 40, -23, -38, 24, 31, -22, -18, 19, 18, 27, -26, -27, 41, -25, 36, -43, 
  -51, 63, 1, 25, 8, 61, -42, -26, -8, -11, 37, -2, -44, 63, -47, 25, -20, 46, 18, -20, -36, 60, 35, -29, -1, -46, 21, 0, 22, 2, -39, 68, 4, 5, 11, 45, -38, -37, 27, 
  -10, -17, -4, -43, 26, 14, 30, -56, -49, -55, 48, 0, -47, -15, -18, 13, -22, -21, 5, -82, -82, -10, 34, -38, -42, 8, -72, 14, 0, -49, 2, -6, -67, -45, -2, -62, -75, 62, 44, 
  50, 15, 14, 25, -74, 62, 60, 4, 46, 41, 16, -56, -45, 54, -27, -50, 56, 45, 72, -56, 55, 3, -25, -55, 14, -40, 62, 32, -42, -4, -19, 62, 4, 17, -36, -86, -69, 31, -47, 
  -22, 3, -76, -47, -29, 27, -38, 21, -56, -52, 38, -58, -24, 6, 6, 26, -56, 30, -63, -67, 24, 28, -6, 12, 51, 31, 48, -51, 37, -10, 25, -16, -22, -59, 38, -20, 69, -5, -49, 
  -65, 13, 49, -50, 42, -51, -41, -2, -39, -33, -14, -32, -33, 34, 6, 11, 33, 49, 41, 77, 32, -61, -10, -11, 40, -24, 45, -16, -66, 42, -7, 22, 43, 8, -50, -37, 69, -43, 7, 
  39, -45, -20, 31, -14, 54, 60, 1, 33, -57, -39, -58, 7, -25, -56, -19, -14, -6, -35, 23, 55, 84, 29, -3, 15, -46, 24, -23, 28, 31, 44, 59, -21, -4, 25, -68, 4, 29, -39, 
  -17, -76, -73, -16, 27, 49, -20, 57, -40, 1, -1, 3, 28, 11, 37, 37, 13, -55, -31, -59, 13, -10, 0, -18, -18, 1, 31, -12, 21, 35, 38, 58, 19, 66, 30, 18, -53, -2, 19, 
  9, -16, 36, 49, 57, 22, 97, 17, 45, 3, -14, -9, 11, -43, 58, -3, -37, 26, 32, 115, 24, -25, -10, -75, -48, -33, -45, 39, -54, -22, 59, 49, -85, 7, -49, -91, -82, -24, 18, 
  56, 4, -14, -36, -39, 85, 55, -4, -3, -58, -10, 12, 26, -1, 42, -60, 6, -4, -4, -28, -26, 40, -60, 11, -61, -73, -4, -4, -19, -30, 44, 20, 55, 73, -63, -66, -61, -5, -31, 
  48, 86, -30, 19, -11, 3, 37, 1, 48, -18, 56, 27, 17, -22, -54, 47, 35, 58, 12, 22, -19, 6, 51, 65, 15, 64, -10, -13, 19, 13, 68, -7, -8, 49, 26, -28, -14, 15, 18, 
  -17, -16, -11, 45, 57, -3, -47, 40, 44, -19, 11, 8, 12, -26, 57, 8, 7, 25, 37, -21, -45, 2, 30, 36, 25, -3, 18, -31, -102, 37, 53, 73, 26, -2, -36, 63, 72, 40, 43, 
  16, 94, 15, 3, 36, -57, -32, 9, 24, 3, 21, 1, -39, -100, -32, -32, -17, 32, -70, -21, -10, -63, -67, -33, -6, -15, 22, 27, 42, -16, 9, 20, 33, 33, 34, 68, -31, 51, 2, 
  8, 18, -78, 45, -27, -43, -17, 22, -16, -44, -7, 12, 6, 42, 75, 0, 24, 19, -2, 5, -66, 23, 27, -28, -43, -22, 38, 18, -58, 43, -47, 65, 27, -12, 0, 62, 36, -46, 54, 
  -59, 24, 34, -53, -45, 40, -17, -5, 46, -28, -27, -35, -1, 0, -9, 13, 17, -5, 6, 71, -62, 18, -45, -28, 21, 5, 22, -46, 13, -46, 39, -16, 1, 11, 5, -14, -38, -52, -40, 
  -9, 67, -10, -37, -15, -3, -39, -2, -28, -10, 21, 39, 33, 41, 48, -3, -12, -12, -4, 73, -14, -74, -61, -32, -34, -32, 33, 48, -7, -60, -25, 31, 48, 66, 64, 76, 7, 89, 57, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 64,39 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0044104987755417824, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,64 } };
const TfArray<1, float> quant7_scale = { 1, { 0.026960443705320358, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,16 } };
const TfArray<1, float> quant8_scale = { 1, { 0.057611994445323944, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfArray<1, float> quant9_scale = { 1, { 0.11580318212509155, } };
const TfArray<1, int> quant9_zero = { 1, { -16 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 39, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 1024, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2496, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension8, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1113007_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1113007_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1113007_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1113007_5_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1113007_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
