; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino, espidf

; Forzamos el tamaño real del chip a 4MB
board_upload.flash_size = 4MB
board_build.partitions = partitions.csv

; Velocidad del monitor serie
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder

; Configuraciones para la placa UWB Pro (habilitar PSRAM)
build_flags = 
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    ; --- DIRECTIVAS PARA LA LIBRERÍA DW1000 ---
    -Wno-error=class-memaccess
    -Wno-error=format-truncation
    -Wno-error=return-type
    ; --- INCLUDES PARA EDGE IMPULSE TINYML ---
    -I lib/ai_model
    -I lib/ai_model/edge-impulse-sdk
    -I lib/ai_model/model-parameters
    -I lib/ai_model/tflite-model
    -I lib/ai_model/edge-impulse-sdk/porting/espressif/esp-dsp/modules/common/include
    -I lib/ai_model/edge-impulse-sdk/porting/espressif/esp-dsp/modules/fft/include
    -I lib/ai_model/edge-impulse-sdk/porting/espressif/ESP-NN/include
    -I lib/ai_model/edge-impulse-sdk/third_party/flatbuffers/include
    -I lib/ai_model/edge-impulse-sdk/third_party/gemmlowp
    -I lib/ai_model/edge-impulse-sdk/third_party/ruy

; Forzamos al compilador a deshabilitar el modo estricto
build_unflags = 
    -Werror=all

; Librerías requeridas para usar la pantalla OLED
lib_deps = 
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit SSD1306 @ ^2.5.9

[env:native]
platform = native
build_src_filter = -<*>